config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root 'pages#home'
  # routes.rb
  get '/tickets/search', to: 'tickets#search'
  get 'users/admin_board', to: 'users#admin_board'


  resources :users, only: [:index, :show, :create, :destroy, :update, :new, :edit] do
    resources :tickets, only: [:index, :show, :create, :destroy, :update, :new, :edit]
  end
  resources :tickets do
    collection do
      get :index_others
    end
    resources :responses, only: [:new, :create, :edit, :update]
    resources :comments, only: [:new, :create]
    resources :attachments, only: [:index, :show, :create, :destroy, :update, :new, :edit]
  end

  resources :tags
  resources :executive_metrics
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :ticket
    belongs_to :executive, class_name: 'User'

    validates :comment, presence: true
    validates :comment, length: { maximum: 500 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @ticket = Ticket.find(params[:ticket_id])
    @comment = @ticket.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @ticket = Ticket.find(params[:ticket_id])
    @executive_id = current_user.id
    @comment_content = params[:comment]
    @comment = Comment.create(comment: @comment_content, ticket_id: @ticket.id, executive_id: @executive_id)

    if @comment.save
      redirect_to @ticket, notice: "Comentario creado correctamente."
    else
      redirect_to @ticket, alert: "Error al crear el comentario."
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.fetch(:comment, {}).permit(:comment, :ticket_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
</div>

app/views/comments/_form.html.erb
<style>

  .card {
    margin-right: 5px;
    margin-left: 5px;
    margin-bottom: 10px;
  }

  .comment-cards {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 20px;
  }

  .comment-card {
    background-color: #f6efef;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .comment-title {
    font-size: 18px;
    font-weight: bold;
    margin-bottom: 10px;
  }

  .no-comment {
    background-color: transparent;
  }

  .comment-details {
    margin-bottom: 5px;
  }

  .icon {
    margin-bottom: 6px;
  }

  .badge-primary {
    background-color: #c14884;
    color: #0f0c0c;
  }

  .badge-secondary {
    background-color: #6a77d8;
    color: #0f0c0c;
  }

  .badge-tertiary {
    background-color: #7aacf0;
    color: #0f0c0c;
  }

  .badge-quaternary {
    background-color: #afe1ec;
    color: #0f0c0c;
  }

  .tags {
    display: flex;
    align-items: center;
    margin-bottom: 10px;
  }

  .tag-badge {
    margin-right: 5px;
    margin-bottom: 5px;
  }

  .response-info {
    margin-top: 20px;
    margin-bottom: 10px;
  }

  .response-text {
    background-color: #f6efef;
    padding: 10px;
    border-radius: 5px;
    margin-bottom: 5px;
  }

  .sep {
    margin-left: 8px;
    margin-right: 8px;
  }

  .tags-icon {
    margin-left: 4px;
    margin-bottom: 4px;
    margin-right: 4px;
  }

  .red-nice {
    background-color: #ff6f69;
    color: #fff;
    padding: 5px 10px;
    border-radius: 3px;
  }

  .yellow-nice {
    background-color: #ffcc5c;
    color: #0f0c0c;
    padding: 5px 10px;
    border-radius: 3px;
  }

  .green-nice {
    background-color: #88d8b0;
    color: #0f0c0c;
    padding: 5px 10px;
    border-radius: 3px;
  }

  .role-badge {
    background-color: #836474;
    margin-left: 10px;
    padding: 5px 10px;
    border-radius: 3px;
    margin-bottom: 10px;
  }
</style>

<head>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
</head>

<body>
  <div id="top-page">

    <div id="wrapper">
      <%= render partial: 'layouts/sidebar' %>

      <div class="container my-5">
        <div class="card">
          <div class="card-body align-items-center justify-content">
            <div>
            <h1>Create a comment</h1>
            </div>

            <%= form_with(model: comment, url: ticket_comments_path(@ticket)) do |form| %>
                <% if comment.errors.any? %>
                  <div style="color: red">
                    <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

                    <ul>
                      <% comment.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>

                <p class = "muted-text">Remember that this comment will be visible to every other executive</p>

                <div class="form-group">
                  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="comment" placeholder = "Write a comment..."></textarea>
                </div>

                <div class="text-center mt-4">
                  <%= form.submit 'Publish Comment', class: 'btn btn-primary' %>
                </div>
                <div>
                  <button class="btn btn-secondary" style = "margin-bottom: 10px;" onclick="history.back()" type = "button">Back</button>
                </div>
              <% end %>
            </div>
          </div>
          <hr style="background-color: #d0d0d0;">
          <h2 style="margin-bottom: -30px;">Commenting on:</h2>
          <%= render partial: 'tickets/ticket' %>
        </div>
      </div>
    </div>
  </div>

</body>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<%= render "form", comment: @comment %>

<br>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_ticket_comment_path(@comment) %> |
</div>