config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root 'pages#home'
  # routes.rb
  get '/tickets/search', to: 'tickets#search'
  get 'users/admin_board', to: 'users#admin_board'


  resources :users, only: [:index, :show, :create, :destroy, :update, :new, :edit] do
    resources :tickets, only: [:index, :show, :create, :destroy, :update, :new, :edit]
  end
  resources :tickets do
    collection do
      get :index_others
    end
    resources :responses, only: [:new, :create, :edit, :update]
    resources :comments, only: [:new, :create]
    resources :attachments, only: [:index, :show, :create, :destroy, :update, :new, :edit]
  end

  resources :tags
  resources :executive_metrics
end

app/models/attachment.rb
class Attachment < ApplicationRecord
    belongs_to :ticket
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: %i[ show edit update destroy ]

  # GET /attachments or /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1 or /attachments/1.json
  def show
    @attachment = Attachment.find(params[:id])
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments or /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to attachment_url(@attachment), notice: "Attachment was successfully created." }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1 or /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to attachment_url(@attachment), notice: "Attachment was successfully updated." }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1 or /attachments/1.json
  def destroy
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to attachments_url, notice: "Attachment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attachment_params
      params.fetch(:attachment, {})
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_attachment.html.erb
<div id="<%= dom_id attachment %>">
</div>

app/views/attachments/_form.html.erb
<%= form_with(model: attachment) do |form| %>
  <% if attachment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
        <% attachment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render "form", attachment: @attachment %>

<br>

<div>
  <%= link_to "Show this attachment", @attachment %> |
  <%= link_to "Back to attachments", attachments_path %>
</div>

app/views/attachments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Attachments</h1>

<div id="attachments">
  <% @attachments.each do |attachment| %>
    <%= render attachment %>
    <p>
      <%= link_to "Show this attachment", attachment %>
    </p>
  <% end %>
</div>

<%= link_to "New attachment", new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render "form", attachment: @attachment %>

<br>

<div>
  <%= link_to "Back to attachments", attachments_path %>
</div>

app/views/attachments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attachment %>

<div>
  <%= link_to "Edit this attachment", edit_attachment_path(@attachment) %> |
  <%= link_to "Back to attachments", attachments_path %>

  <%= button_to "Destroy this attachment", @attachment, method: :delete %>
</div>