config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root 'pages#home'
  # routes.rb
  get '/tickets/search', to: 'tickets#search'
  get 'users/admin_board', to: 'users#admin_board'


  resources :users, only: [:index, :show, :create, :destroy, :update, :new, :edit] do
    resources :tickets, only: [:index, :show, :create, :destroy, :update, :new, :edit]
  end
  resources :tickets do
    collection do
      get :index_others
    end
    resources :responses, only: [:new, :create, :edit, :update]
    resources :comments, only: [:new, :create]
    resources :attachments, only: [:index, :show, :create, :destroy, :update, :new, :edit]
  end

  resources :tags
  resources :executive_metrics
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attachment.rb
class Attachment < ApplicationRecord
    belongs_to :ticket
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :ticket
    belongs_to :executive, class_name: 'User'

    validates :comment, presence: true
    validates :comment, length: { maximum: 500 }
end

app/models/executive_metric.rb
class ExecutiveMetric < ApplicationRecord
    belongs_to :executive, class_name: 'User'
    belongs_to :ticket
  end
 

app/models/response.rb
class Response < ApplicationRecord
    belongs_to :ticket
    belongs_to :executive, class_name: 'User'
    belongs_to :requiring_user, class_name: 'User'
    
    after_create do
        if evaluation.present?
            create_executive_metric
        end
    end

    after_update do
        if evaluation.present?
            create_executive_metric
        end
    end

    private
    def create_executive_metric
        ExecutiveMetric.create(date: Date.today, type_of_metric: "Evaluation", evaluation: self.evaluation, executive_id: self.executive_id, ticket_id: self.ticket_id)
    end

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tags_tickets
    has_many :tickets, through: :tags_tickets
  end  

app/models/tags_ticket.rb
class TagsTicket < ApplicationRecord
    belongs_to :ticket
    belongs_to :tag
end
  

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :executive, class_name: 'User'
    belongs_to :requiring_user, class_name: 'User'
    has_many_attached :attachments
    has_many :comments
    has_many :responses
    has_many :executive_metrics
    has_many :tags_tickets
    has_many :tags, through: :tags_tickets
    validate :resolution_date_greater_than_creation_date

    after_create do
        creation_executive_metric
        opened_or_closed_executive_metric
    end

    before_update do
        if state_changed? && state_was == "open" && state == "closed"
            change_metric
        end
        if state_changed? && state_was == "closed" && state == "reopened"
            change_metric_reopened
        end
    end

    before_destroy do
        destroy_dependent_records
    end
    
    private
    def resolution_date_greater_than_creation_date
        return unless resolution_date && creation_date
    
        errors.add(:resolution_date, "Resolution date must be greater than creation date") if resolution_date <= creation_date
    end

    def creation_executive_metric
        ExecutiveMetric.create(executive_id: self.executive_id, date: Date.today, type_of_metric: "create", ticket_id: self.id)
    end

    def opened_or_closed_executive_metric
        if state == "open"
            ExecutiveMetric.create(executive_id: self.executive_id, date: Date.today, type_of_metric: "open", ticket_id: self.id)
        end
        if state == "closed"
            ExecutiveMetric.create(executive_id: self.executive_id, date: Date.today, type_of_metric: "closed", ticket_id: self.id)
        end
    end

    def change_metric
        ex = ExecutiveMetric.find_by(ticket_id: self.id)
        ex.update(type_of_metric: "closed") if ex.present?
    end

    def change_metric_reopened
        ex = ExecutiveMetric.find_by(ticket_id: self.id)
        ex.update(type_of_metric: "reopened") if ex.present?
    end

    def destroy_dependent_records
        attachments.destroy_all
        comments.destroy_all
        responses.destroy_all
        executive_metrics.destroy_all
        tags.clear
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable
    validates :email, uniqueness: true
    validates :email, presence: true
    validate :only_one_administrator
    has_many :executive_tickets, class_name: 'Ticket', foreign_key: 'executive_id'
    has_many :requiring_user_tickets, class_name: 'Ticket', foreign_key: 'requiring_user_id'
    has_many :executive_metrics, class_name: 'ExecutiveMetric', foreign_key: 'executive_id'
    has_many :executive_responses, class_name: 'Response', foreign_key: 'executive_id'
    has_many :requiring_user_responses, class_name: 'Response', foreign_key: 'requiring_user_id'

    attribute :role, :integer, default: 0

    enum role: {
        requiring_user: 0,
        executive: 1,
        supervisor: 2,
        administrator: 3
    }

    private
    def only_one_administrator
        if role == "administrator"
            if User.exists?(role: "administrator")
                errors.add(:role, 'there can only be one admin')
            end
        end
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
    @tag = Tag.find(params[:id])
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.tags_tickets.destroy_all
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.fetch(:tag, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/executives_helper.rb
module ExecutivesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/supervisors_helper.rb
module SupervisorsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tags_tickets_helper.rb
module TagsTicketsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
    <div class="alert alert-success" role="alert">
        <%= notice %>
    </div>
<% end %>
<% if alert %>
    <div class="alert alert-danger" role="alert">
        <%= alert %>
    </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<style>
.log-out-button {
    background-color: transparent;
    border: none;
    padding: 0;
}

.color-custom {
    background-color: #1d1d1d;
    margin-right: 10px;
}

.nav-item {
    font-size: 1.2em;
}

.nav-link {
    color: 	#d6d7d4;
}

.nav-link:hover {
    color: #f3f9fb;
    text-decoration: none;
}

.sidebar-divider {
    background-color: #d0d0d0;
}

</style>

<body>

<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<ul class="navbar-nav color-custom sidebar accordion" id="accordionSidebar">

<div class="sidebar-brand d-flex align-items-center justify-content-center">
    <div class="sidebar-brand-text mx-3" style = "color: #eeeeee;">Welcome, <%= current_user.name %>!</div>
</div>

<hr class="sidebar-divider my-0">

<!-- Nav Item - Dashboard -->
<li class="nav-item active">
    <a class="nav-link" href="/">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Home</span></a>
</li>

<!-- Divider -->
<hr class="sidebar-divider" >

<li class="nav-item">
    <a class="nav-link" href="<%= user_path(current_user) %>">
        <i class="material-icons">face</i>
        <span>My Profile</span></a>
</li>

<% if current_user.requiring_user? || current_user.executive? %>
    <li class="nav-item">
        <a class="nav-link" href="<%= user_tickets_path(current_user) %>">
            <i class="fas fa fa-ticket"></i>
            <span>My Tickets</span>
        </a>
    </li>
<% end %>

<% if current_user.executive? %>
    <li class="nav-item">
        <a class="nav-link" href="<%= index_others_tickets_path %>">
            <i class="fas fa fa-ticket"></i>
            <span>Other Tickets</span>
        </a>
    </li>
<% end %>

<% if current_user.supervisor? || current_user.administrator? %>

    <li class="nav-item">
    <a class="nav-link" href="<%= tickets_path %>">
        <i class="fas fa fa-ticket"></i>
        <span>Tickets</span>
    </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="<%= executive_metrics_path %>">
            <i class='fas fa-chart-line'></i>
            <span>Executive Metrics</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="/users/admin_board">
            <i class="bi bi-controller"></i>
            <span>Roles Administrator Panel</span>
        </a>
    </li>
<% end %>

<hr class="sidebar-divider">

<li class="nav-item">
  <%= button_to destroy_user_session_path, method: :delete, class: "nav-link log-out-button custom-link" do %>
    <i class="fas fa-power-off"></i>
    <span>Log out</span>
  <% end %>
</li>





<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">

<!-- Sidebar Toggler (Sidebar) -->
<div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
</div>

</ul>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <%= stylesheet_link_tag 'my_styles', media: 'all' %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  <!-- Custom fonts for this template-->
  <%= stylesheet_link_tag 'fontawesome-free/css/all.min.css' %>
  <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet">

  <!-- Custom styles for this template-->
  <%= stylesheet_link_tag 'sb-admin-2.min.css' %>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

</head>

<script>
document.getElementById('sidebarToggle').addEventListener('click', function() {
  document.getElementById('accordionSidebar').classList.toggle('toggled');
});
</script>

<body>
<script>
  document.getElementById('sidebarToggle').addEventListener('click', function() {
    document.getElementById('accordionSidebar').classList.toggle('toggled');
  });
</script>

  <%= render partial: 'layouts/messages' %>
  <%= yield %>
</body>

<script>
  document.getElementById('sidebarToggle').addEventListener('click', function() {
    document.getElementById('accordionSidebar').classList.toggle('toggled');
  });
</script>

</html>

app/views/pages/_no_open_tickets.html.erb
<h3 class="h3 mb-0 text-gray-800" style = "margin-top: 5px; margin-bottom: 20px;">Open Tickets</h3>
<div id="content-wrapper" class="d-flex flex-column" style = "background-image: linear-gradient(to top, #dad4ec 0%, #dad4ec 1%, #f3e7e9 100%);">
    <div id="content">
        <div class="container-fluid">
            <div class="ticket-response-section">
                <div class="card shadow mb-4 no-open-tickets">
                    <div class="card-header py-3" style="margin-bottom: -8px; background-color: rgba( 248, 249, 252, 0.3);">
                        <h6 class="m-0 font-weight-bold text-primary">There are no open tickets</h6>
                    </div>

                    <div class="card-body" style="display: flex; flex-direction: column;">
                        <i class="bi bi-emoji-laughing" style = "margin-top: 5px; margin-bottom: 12px; margin-left: 8px;"></i>
                        <a href="<%= user_tickets_path(current_user) %>" class="btn btn-primary" style="width: 180px;">See all my tickets</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/_open_ticket.html.erb
<style>
    .no-response {
        background-color: transparent;
    }

    .no-open-tickets {
        background-color: transparent;
    }

    .red-nice {
    background-color: #ff6f69;
    }

    .yellow-nice {
    background-color: #ffcc5c;
    }

    .green-nice {
    background-color: #88d8b0;
    }
</style>


<h3 class="h3 mb-0 text-gray-800" style = "margin-top: 5px; margin-bottom: 20px;">Open Tickets</h3>
<div id="content-wrapper" class="d-flex flex-column" style = "background-image: linear-gradient(to top, #dad4ec 0%, #dad4ec 1%, #f3e7e9 100%);">
    <div id="content">
        <div class="container-fluid">
            <div class="ticket-response-section">
                <div class="card shadow mb-4">
                    <div class="card-header py-3" style = "color: #2a4454; margin-bottom: -8px;">
                        <h6 class="m-0 font-weight-bold text-primary"><%= open_ticket.title %></h6>
                    </div>
                    <div class="card-body">
                        <div class = "badges-priority">
                            <% if open_ticket.priority == 1 %>
                            <sup><span class="badge rounded-pill red-nice">High Priority</span></sup>
                            <% elsif open_ticket.priority == 2 %>
                                <sup><span class="badge rounded-pill yellow-nice">Medium Priority</span></sup>
                            <% elsif open_ticket.priority == 3 %>
                                <sup><span class="badge rounded-pill green-nice">Low Priority</span></sup>
                            <% end %>
                        </div>
                    <div style = "display: flex;">
                        <span class="icon me-1"><i class="far fa-calendar-alt"></i></span>
                        <p class="ticket-details">Creation Date: <%= open_ticket.creation_date %></p>
                    </div>
                    <% if open_ticket.resolution_date %>
                        <div style = "display: flex;">
                            <span class="icon me-1"><i class="far fa-calendar-check"></i></span>
                            <p class="ticket-details">Resolution Date: <%= open_ticket.resolution_date %></p>
                        </div>
                    <% end %>
                    <p> <%= open_ticket.description %></p>
                    <a href="<%= ticket_path(open_ticket) %>" class="btn btn-primary">See ticket</a>
                </div>
            </div>
        </div>
    </div>
</div>